name: build
on:
  push:
    branches:
      - main

concurrency:
  group: build-workflow
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          commit_sha=${{ github.sha }}
          parent_sha=$(git rev-parse ${commit_sha}^ | xargs echo -n)

          git diff --name-only ${commit_sha} ${parent_sha}~1 > changed.txt
          echo "CHANGED:
          cat changed.txt

          cat changed.txt | cut -d'/' -f1 | uniq > changed_top.txt
          echo "CHANGED TOP:
          cat changed_top.txt

          grep "mikrodatorprojekt" changed_top.txt >> needs-update.txt
          echo "NEEDS UPDATE:"
          cat needs-update.txt
      - run: grep -A 1 "#import .*" mikrodatorprojekt/main.typ > requirements.typ
      - uses: typst-community/setup-typst@v4
        with:
          cache-dependency-path: requirements.typ
      - run: mkdir build
      - run: typst compile mikrodatorprojekt/main.typ build/mikrodatorprojekt.pdf
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: build

  tag:
    needs: render
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - run: |
          github_sha_hash=${{ github.sha }}
          github_sha_short="${github_sha_hash:0:7}"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add build
          git commit -m "build ${github_sha_short}"
          git tag "build-${github_sha_short}"
          git tag -f build-latest
      - uses: ad-m/github-push-action@master
        with:
          force: true
          tags: true
          branch: build
