name: build
on:
  push:
    branches:
      - main

concurrency:
  group: build-workflow
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest
    outputs:
      needs_update: ${{ steps.find_changed.outputs.needs_update }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create build directory
        run: mkdir build
      - id: find_changed
        name: Find changed projects
        run: |
          commit_sha=${{ github.sha }}
          parent_sha=$(git rev-parse "${commit_sha}^" | xargs echo -n)
          git diff --name-only ${commit_sha} ${parent_sha} > build/changed_files.txt
          cut -d'/' -f1 build/changed_files.txt | uniq > build/changed_top_level.txt
          ( grep "mikrodatorprojekt" build/changed_top_level.txt || [ "$?" == "1" ] ) >> build/needs_update.txt
          needs_update_count=$(cat build/needs_update.txt | wc -l | xargs echo -n)
          echo "needs_update=${needs_update_count}" >> "$GITHUB_OUTPUT"
      - name: Compute Typst dependencies
        run: grep -A 1 "#import .*" mikrodatorprojekt/main.typ | uniq > build/requirements.typ
      - uses: typst-community/setup-typst@v4
        with:
          cache-dependency-path: build/requirements.typ
      - name: Build mikrodatorprojekt
        run: typst compile mikrodatorprojekt/main.typ build/mikrodatorprojekt.pdf
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: build

  tag:
    needs: render
    if: ${{ needs.render.outputs.needs_update != "0" }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Create build tag
        run: |
          commit_sha=${{ github.sha }}
          commit_sha_short="${commit_sha:0:7}"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add build
          git commit -m "build ${commit_sha_short}"
          git tag "build-${commit_sha_short}"
          git tag -f build-latest
      - uses: ad-m/github-push-action@master
        with:
          force: true
          tags: true
          branch: build
