name: update-metadata
on:
  push:
    branches:
      - main

concurrency:
  group: update-metadata-workflow
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  update-metadata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          ls projects > project-list.txt
          echo project-list.txt
